### ISSUE TITLE
After using app.hide(), callback fired after click INSIDE window

### ISSUE THREAD

**Issue by romaincointepas** [mullvad/NSEventMonitor#6] opened 2017-05-15 23:26 UTC
In the example, add `app.hide()` below every `window.hide()`, then:

**First way to reproduce**
- click on tray icon (window shows)
- click again on tray icon (window hides)
- click again on tray icon (window shows again)
- click on desktop (directly on the desktop image, not on an app)
- click INSIDE the window, `.start` callback is called, window hides

**Second way to reproduce**
- click on tray icon (window shows)
- right-click INSIDE another app (window hides)
- click again on tray icon (window shows again)
- click INSIDE the window, `.start` callback is called, window hides

`app.hide()` is used to regive focus to the previous app (`window.hide()` doesn't do that), this was recommended by one of the Electron dev.

*Note: this is one of the issues I was seeing, see #3.*

**Comment by pronebird** [comment] 2017-05-16 11:12
I can reproduce that, using `app.hide()` instead of `window.hide()` causes clicks to be registered by global observer. Not sure what I can do about that, if system dispatches the event to its own window it means it does not see that window or something like that..

**Comment by romaincointepas** [comment] 2017-05-16 12:11
Maybe an alternative to handle all cases would be to fire click events from everywhere, attach a click position object to the callback, and let the app itself decide what to do (like ignoring the event if the click position is inside some bounds).

Right now I see 3 mishandled cases that could be solved with the above:
1. Clicking on desktop (desktop image) doesn't fire anything.
2. Using `app.quit()` instead of `window.hide()` will fire events even when clicks happen inside the app window.
3. No click/right-click event fired on the tray icon when a custom tray context menu is currently being shown.

**Comment by pronebird** [comment] 2017-05-16 15:43
1. is not valid as mentioned in #5 due to use of undocumented feature in Finder.
2. I am not really sure what is going on there, but I can confirm that `app.hide()` acts different from `window.hide()`. Once again we use public API to observe clicks, if it fires it means that something fishy is going on in `app.hide()`. It works fine with `window.show` or `window.hide` though.
3. At the moment this module only observes events dispatched to other apps. Usually you have better means to observe events originating from Tray icon, or your window, etc..

**Comment by pronebird** [comment] 2018-11-08 11:41
Closing this because I think this was in relation to using undocumented Finder setting `CreateDesktop false`. Please re-open if you still experience this. I am not able to reproduce this.

**Closed by pronebird** 2018-11-08 11:41 UTC
